name: timelines

services:
  core.db:
    container_name: core.db
    image: postgres
  
  core.api:
    container_name: core.api
    image: ${DOCKER_REGISTRY-}coreapi
    build:
      context: ../Backend
      dockerfile: src/Applications/Core/Core.Api/Dockerfile

volumes:
  timelines_core: