name: timelines

services:
  tl-api:
    container_name: tl-api
    image: ${DOCKER_REGISTRY-}tl-api
    networks:
      - main
    depends_on:
      - tl-database
    build:
      context: ../Backend
      dockerfile: src/Applications/Core/Core.Api/Dockerfile

  tl-database:
    container_name: tl-database
    image: postgres
    networks:
      - main

  proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    networks:
      - main
    depends_on:
      - tl-api
    ports:
      - "80:80"
      - "443:443"

networks:
  main:
    driver: bridge

volumes:
  timelines_core:
