name: timelines

services:
    tl-api:
        container_name: tl-api
        image: ${DOCKER_REGISTRY-}tl-api
        networks:
            - tl-network
        depends_on:
            - tl-database
        build:
            context: ../Backend
            dockerfile: src/Applications/Core/Core.Api/Dockerfile

    tl-frontend:
        container_name: tl-frontend
        image: ${DOCKER_REGISTRY-}tl-frontend
        networks:
            - tl-network
        depends_on:
            - tl-api
        build:
            context: ../Frontend/react-app

    tl-database:
        container_name: tl-database
        image: postgres
        networks:
            - tl-network

networks:
    tl-network:
        driver: bridge

volumes:
    timelines_core:
