name: timelines

services:
    tl-api:
        container_name: tl-api
        image: ${DOCKER_REGISTRY-}tl-api
        build:
            context: ../Backend
            dockerfile: src/Applications/Core/Core.Api/Dockerfile

    tl-frontend:
        container_name: tl-frontend
        image: ${DOCKER_REGISTRY-}tl-frontend
        build:
            context: ../Frontend/react-app

    tl-database:
        container_name: tl-database
        image: postgres

volumes:
    timelines_core:
