// <auto-generated />
using System;
using System.Collections.Generic;
using Files.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
using Notes.Infrastructure.Data;
========
>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
namespace Notes.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20250425125623_NotesInit")]
    partial class NotesInit
========
namespace Files.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FilesDbContext))]
    [Migration("20250423130749_FilesInit")]
    partial class FilesInit
>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
                .HasDefaultSchema("Notes")
                .HasAnnotation("ProductVersion", "9.0.1")
========
                .HasDefaultSchema("Files")
                .HasAnnotation("ProductVersion", "9.0.0")
>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
            modelBuilder.Entity("Notes.Domain.Models.Note", b =>
========
            modelBuilder.Entity("Files.Domain.Models.FileAsset", b =>
>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");
========
                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");
>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
========
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs
                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Owner")
========
                    b.Property<string>("Name")
>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
                    b.Property<string>("RelatedNotes")
                        .HasColumnType("text")
                        .HasColumnName("RelatedNotes");

                    b.Property<string>("SharedWith")
                        .HasColumnType("text")
                        .HasColumnName("SharedWith");
========
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");
>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SharedWith")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<float>("Size")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

<<<<<<<< HEAD:Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20250425125623_NotesInit.Designer.cs
                    b.ToTable("Notes", "Notes");
========
                    b.ToTable("Files", "Files");
>>>>>>>> main:Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20250423130749_FilesInit.Designer.cs
                });
#pragma warning restore 612, 618
        }
    }
}
