# This override file uses environment variables defined in a .env file.
# Do not commit actual .env files with secrets.

services:
  tl-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ConnectionStrings__DefaultConnection=Host=tl-database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
    restart: unless-stopped
    ports:
      - "26000:8080"

  tl-database:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - "25432:5432"
    volumes:
      - timelines_core:/var/lib/postgresql/data

  proxy:
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/frontend:/usr/share/nginx/html:ro
