name: Enforce branch naming

on:
    pull_request:
        branches:
            - dev
            - main

jobs:
    validate-branch-name:
        runs-on: ubuntu-latest
        steps:
            - name: Check branch name
              run: |
                  BRANCH_NAME="${{ github.head_ref }}"

                  echo "🔍 Checking: $BRANCH_NAME"

                  if [[ ! "$BRANCH_NAME" =~ ^(feature|fix|chore|refactoring|release)/.+$ && ! "$BRANCH_NAME" =~ ^jssbg.*$ ]]; then
                    echo "❌ Invalid branch name: $BRANCH_NAME"
                    echo "👉 Branch name must begin with 'jssbg', 'feature/', 'fix/', 'chore/', 'refactoring/' or 'release/'"
                    exit 1
                  fi

                  echo "✅ Valid branch name: $BRANCH_NAME"
